### ISSUE TITLE
Delete grammar source files after build

### ISSUE THREAD

**Issue by ChrHorn** [helix-editor/homebrew-helix#10]
During the build process Helix will download and compile the tree-sitter grammar source files. The source files are only needed for the build process and take a lot of space (about 660MB). The `runtime/grammars/sources` folder should be deleted after the `cargo install` step.

**Comment by the-mikedavis** [comment]
I opened up https://github.com/Homebrew/homebrew-core/pull/108657 to address it upstream. I'll push a change here too.

**Comment by the-mikedavis** [comment]
Closed in https://github.com/helix-editor/homebrew-helix/commit/71863a904987915988c719fff6ff7943809c8082
