### ISSUE TITLE
Error when installing with Homebrew on MacOS

### ISSUE THREAD

**Issue by devanlooches** [helix-editor/homebrew-helix#8]
### Summary

When I try to install helix with homebrew I get the following error:
```
Error: An exception occurred within a child process:
  Errno::ENOENT: No such file or directory - contrib/completion/hx.bash
```
This only happened with the newest version 22.05. 
I was able to install 22.03 correctly but as soon as I tried 22.05 it had this error.

### Reproduction Steps

 

1. brew untap helix-editor/helix
2. brew install helix

### Platform

macOS

### Terminal Emulator

wezterm

### Helix Version

helix 22.05

**Comment by the-mikedavis** [comment]
https://github.com/helix-editor/homebrew-helix/pull/6

The new completion stuff might need some tuning

**Comment by archseer** [comment]
\cc @d12bb

**Comment by the-mikedavis** [comment]
For now I pushed a commit to revert the completion changes: 2564f88

**Comment by devanlooches** [comment]
Cool thank you that fixed it!

**Comment by d12bb** [comment]
Sorry my bad, I only tested using head and my local repo with the completions already added initially and missed that a glob is used to install stable, causing the completion files also to be moved (btw, that [is considered bad practice](https://docs.brew.sh/Formula-Cookbook#just-moving-some-files)). Fixed it by moving the completion block above in #9.
